#!/bin/bash
set -e

cd $OPENSHIFT_DATA_DIR
make -f $OPENSHIFT_REPO_DIR/.openshift/Makefile

pecl config-set php_ini $OPENSHIFT_DATA_DIR/php/lib/php.ini
pecl install raphf || pecl upgrade raphf
pecl install propro || pecl upgrade propro
pecl install pecl_http || pecl upgrade pecl_http
